title: "Whisper Speech App"
description: "Privacy-focused desktop app for speech-to-text using OpenAI Whisper"
url: "https://suhanichawla.github.io"
baseurl: "/whisper-on-prem"

# GitHub Pages settings
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO settings
author: "Suhani Chawla"
twitter:
  username: YOUR_TWITTER_HANDLE

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
